# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=15, unique=True, verbose_name='Administration Id')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('other_names', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Names')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50, verbose_name='Gender / Sex')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Miss')], max_length=50, verbose_name='Title')),
                ('hiredate', models.DateField(verbose_name='Hire Date')),
                ('admin_type', models.CharField(choices=[('Head Master / Mistress', 'Head Master / Mistress'), ('Ass. Head Master / Mistress', 'Ass. Head Master / Mistress')], max_length=50, verbose_name='Administration Type')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Profile Image')),
                ('post_address', models.CharField(max_length=100, verbose_name='Postal Address')),
                ('home_address', models.CharField(max_length=100, verbose_name='Home Address')),
            ],
            options={
                'verbose_name': 'Administration Profile',
                'verbose_name_plural': 'Administration Profile',
            },
        ),
    ]
