# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=15, unique=True, verbose_name='Parent Id')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('other_names', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Names')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50, verbose_name='Gender / Sex')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Miss')], max_length=50, verbose_name='Title')),
                ('relation', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Other', 'Other')], max_length=50, verbose_name='Relation')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Profile Image')),
                ('post_address', models.CharField(max_length=100, verbose_name='Postal Address')),
                ('home_address', models.CharField(max_length=100, verbose_name='Home Address')),
            ],
            options={
                'verbose_name': 'Parents Profile',
                'verbose_name_plural': 'Parents Profile',
            },
        ),
    ]
